### ISSUE TITLE
Re-build the aws batch stack using cloudformation

### ISSUE THREAD

**Issue by cornhundred** [ismms-himc/cellranger-aws-pipeline#5]
The branch 

https://github.com/ismms-himc/cellranger-aws-pipeline/tree/tutorial

contains instructions on how to set up AWS batch using cloudformation. I think we might want to re-set-up our batch system using cloudformation

**Comment by ryan-williams** [comment]
Nick cleaned up the tutorial and put it in this repo https://github.com/ismms-himc/aws-batch-cellranger-tiny-bcl

**Comment by ryan-williams** [comment]
think this is done
