### ISSUE TITLE
run and document tiny-bcl on himc AWS Batch

### ISSUE THREAD

**Issue by cornhundred** [ismms-himc/cellranger-aws-pipeline#8]
@cornhundred will document re-running of the tiny-bcl run on the HIMC AWS

**Comment by cornhundred** [comment]
@cornhundred is working on this in this repo https://github.com/ismms-himc/aws-batch-cellranger-tiny-bcl

**Comment by cornhundred** [comment]
The tiny-bcl example runs on HIMC AWS. Documentation for setting up the AWS stack (via cloudformation) can be found in the following repo: 

https://github.com/ismms-himc/aws-batch-cellranger-tiny-bcl

The next steps are to break the job into:
* a single mkfastq run
* multiple count runs on the demultiplexed FASTQ files

**Comment by ryan-williams** [comment]
That repo should be folded into this one; it's naturally grown to contain a lot of stuff not specific to running on tiny-bcl: https://github.com/ismms-himc/aws-batch-cellranger-tiny-bcl/issues/1

**Comment by cornhundred** [comment]
@ryan-williams I'm thinking the repo https://github.com/ismms-himc/aws-batch-cellranger-tiny-bcl will eventually get a name change and be where the new pipeline lives. I don't want to bring it into this repo if it ends up re-building everything. If that ends up happening, we can deprecate this repo.

**Comment by cornhundred** [comment]
@ryan-williams it would be so much easier to talk in person. We'll discuss in our next meeting

**Comment by ryan-williams** [comment]
added that one as a submodule; closing
